title: Local IIIF Annotation Server
description: ""
baseurl: "/annotate"
url: "https://dnoneill.github.io"

markdown: kramdown
permalink: pretty

theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

exclude: [Rakefile, Gemfile*, vendor]
include: [feed.xml]

collections:
  annotations:
    output: true
    permalink: /annotations/:name
  helpdocs:
    output: true
    permalink: /help/:name
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

api_server: https://limitless-plains-74009.herokuapp.com/annotations/

exclude:
  - ENV/
  - imported_roles
