title: Local IIIF Annotation Server
description: ""
baseurl: "/annotate"
url: "http://dnoneill.github.io"

markdown: kramdown
permalink: pretty

github_username: mnyrop
social_username: mariinyrop

theme: jekyll-swiss

exclude: [Rakefile, Gemfile*, vendor]
include: [feed.xml]

collections:
    annotations: 
        output: true
        permalink: /annotations/:name
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
plugins:
  - jekyll-admin
