title: Local IIIF Annotation Server
description: "Local IIIF annotation server that allows for easy annotation creation."
baseurl: "/annotate"
url: "https://dnoneill.github.io"

markdown: kramdown
permalink: pretty

theme: jekyll-materialdocs
remote_theme: chromatical/jekyll-materialdocs
plugins:
  - jekyll-seo-tag

exclude: [Rakefile, Gemfile*, vendor]
include: [feed.xml]


collections:
  annotations:
    output: true
    permalink: /annotations/:name
  ranges:
    output: true
    permalink: /ranges/:name
  helpdocs:
    output: true
    permalink: /help/:name
  annotation_data:
    output: true
    permalink: /annotations/:name
  iiifproviders:
    permalink: /:path
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

api_server: https://limitless-plains-74009.herokuapp.com/annotations/
endpoint: https://limitless-plains-74009.herokuapp.com/write_annotation/

exclude:
  - ENV/
  - imported_roles

lunr_settings:
  collections: [annotation_data]
  atozsortfield: slug
  displayfields:
    - {field: slug, headerfield: true, highlight: false}
    - {field: imagescr, headerimage: true, highlight: false}
  fields:
  - boost: 10
    jekyllfields: [content]
    searchfield: content
  - boost: 10
    jekyllfields: [tags]
    searchfield: tags
    facetfield: true

  fuzzysearchfields: [content]
