title: Local IIIF Annotation Server
description: ""
baseurl: "/annotate"
url: "https://dnoneill.github.io"

markdown: kramdown
permalink: pretty

theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

exclude: [Rakefile, Gemfile*, vendor]
include: [feed.xml]


collections:
  annotations:
    output: true
    permalink: /annotations/:name
  helpdocs:
    output: true
    permalink: /help/:name
  annotation_data:
    output: true
    permalink: /annotations/:name
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

api_server: https://limitless-plains-74009.herokuapp.com/annotations/

exclude:
  - ENV/
  - imported_roles

lunr_settings:
  collections: [annotation_data]
  atozsortfield: slug
  displayfields:
    - {field: slug, headerfield: true, highlight: false}
  fields:
  - boost: 10
    jekyllfields: [content]
    searchfield: content
  - boost: 10
    jekyllfields: [tags]
    searchfield: tags
    facetfield: true

  fuzzysearchfields: [content]