title: Local IIIF Annotation Server
description: ""
baseurl: "/annotate"
url: "https://dnoneill.github.io"

markdown: kramdown
permalink: pretty

theme: jekyll-swiss

exclude: [Rakefile, Gemfile*, vendor]
include: [feed.xml]

collections:
    annotations: 
        output: true
        permalink: /annotations/:name
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
