title: Local IIIF Annotation Server
description: ""
baseurl: "/annotate"
url: "https://dnoneill.github.io"

markdown: kramdown
permalink: pretty

theme: jekyll-theme-hydeout

exclude: [Rakefile, Gemfile*, vendor]
include: [feed.xml]

collections:
    annotations:
        output: true
        permalink: /annotations/:name
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

api_server: http://0.0.0.0:5000/annotations/

github_username: ncsu-libraries

exclude:
  - ENV/

aux_links:
  "Local IIIF Annotation Server on GitHub":
    - "//github.com/dnoneill/annotate"
