title: Local Annotation Server
description: "Local annotation server that allows for easy annotation creation."
baseurl: "/annotate"

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag

exclude: [Rakefile, Gemfile*, vendor]
include: [feed.xml]

theme: annotate-theme

collections:
  annotations:
    output: true
    permalink: /annotations/:name
  ranges:
    output: true
    permalink: /ranges/:name
  annotation_data:
    output: true
    permalink: /annotations/:name

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

api_server: http://0.0.0.0:5000/
endpoint: http://0.0.0.0:5000/write_annotation/

exclude:
  - ENV/
  - imported_roles

lunr_settings:
  collections: [annotation_data]
  atozsortfield: slug
  displayfields:
    - {field: slug, headerfield: true, highlight: false}
    - {field: imagescr, headerimage: true, highlight: false}
  fields:
  - boost: 10
    jekyllfields: [content]
    searchfield: content
  - boost: 10
    jekyllfields: [tags]
    searchfield: tags
    facetfield: true

  fuzzysearchfields: [content]
