title: Local IIIF Annotation Server
description: ""
baseurl: "/annotate"
url: "https://dnoneill.github.io"

markdown: kramdown
permalink: pretty

theme: jekyll-readthedocs
remote_theme: pawamoy/jekyll-readthedocs

exclude: [Rakefile, Gemfile*, vendor]
include: [feed.xml]

collections:
    annotations:
        output: true
        permalink: /annotations/:name
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

api_server: https://limitless-plains-74009.herokuapp.com/annotations/

exclude:
  - ENV/

aux_links:
  "Local IIIF Annotation Server on GitHub":
    - "//github.com/dnoneill/annotate"
